### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by jpculp**
**Testing done:**

Updated small group of 3 bottlerocket nodes. (thanks, @gthao313!)

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by jpculp** [comment]
Rebased to see if it fixes the CI issue.

**Comment by stmcginnis** [comment]
> Rebased to see if it fixes the CI issue.

Maybe the runner has a different rust version than your local version?

```
Run rustup update stable
  rustup update stable
  shell: /usr/bin/bash -e {0}
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

info: checking for self-updates
  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.64.0 (a55dd71d5 [2](https://github.com/bottlerocket-os/bottlerocket-update-operator/actions/runs/3185020300/jobs/5194097834#step:4:2)022-0[9](https://github.com/bottlerocket-os/bottlerocket-update-operator/actions/runs/3185020300/jobs/5194097834#step:4:10)-19)

warning: tool `rustfmt` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `cargo-fmt` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
```

**Comment by jpculp** [comment]
> Maybe the runner has a different rust version than your local version?

I built locally on x86_64 and aarch64 using rust 1.64.0 and rust 1.61.0 (the version in the Bottlerocket SDK) prior to the rebase, but the weird linking error is still occurring. Since this isn't a high priority I'll drop it into draft and we can poke at it a bit more.

**Comment by jpculp** [comment]
Dropped `integ` commit (for now).

**Comment by jpmcb** [comment]
Is this the linking error you saw? https://github.com/bottlerocket-os/bottlerocket-update-operator/actions/runs/3184235579/jobs/5192405098#step:5:343

Those look to have started a few hours ago 👀

**Comment by jpculp** [comment]
> Is this the linking error you saw? https://github.com/bottlerocket-os/bottlerocket-update-operator/actions/runs/3184235579/jobs/5192405098#step:5:343
> 
> Those look to have started a few hours ago 👀

The very same. We merged a couple dependabot updates this morning, but each of those were rebased and retested prior to merge.

Checking to see if bumping the builder image helps.

**Comment by jpculp** [comment]
Temporarily taking caching out of the picture to make sure we aren't running out of disk space.

**Comment by jpculp** [comment]
Removed testing commit and rebased now that we've cleared the cache.

**Review by gthao313 — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]
Deployed the controller / resources and all looks well! Thanks Patrick! 👏🏼

**Pull request merged**
