### PR TITLE
feat(helm-chart): enable podlabels configuration

### PR DESCRIPTION
**Pull request by danielvvoros**
**Issue number:** https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/616

**Description of changes:** Add optional `podLabels` to the Deployment and DaemonSet.

**Testing done:** Yes, only locally.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by alexandrempm** [comment]
Great :-)

**Review by alexandrempm — APPROVED** [review]

**Review by alexaln30 — APPROVED** [review]
LGTM

**Review by ArthurHLG — APPROVED** [review]

**Comment by ArthurHLG** [comment]
Approved

**Review by chmodrs — APPROVED** [review]

**Comment by ytsssun** [comment]
Hi @danielvincenzi, thanks for cutting us this PR. I have done below tests to verify the behavior and it is working fine for me:

1. Upgrade the brupop via local chart
2. Use a sample `value.yaml`. 
```
scheduler_cron_expression: '* 23 * * * Sun *'
podLabels:
  app: "brupop-test"
  environment: "beta"
```
3. Run `helm upgrade brupop-operator deploy/charts/bottlerocket-update-operator -f values.yaml`
4. Get the pods labels:
```
» kubectl get pods --namespace brupop-bottlerocket-aws --show-labels                                                   1 ↵
NAME                                         READY   STATUS    RESTARTS   AGE     LABELS
brupop-agent-dlppb                           1/1     Running   0          3m13s   app=brupop-test,brupop.bottlerocket.aws/component=agent,controller-revision-hash=67b54459db,environment=beta,pod-template-generation=3
brupop-agent-ffrtw                           1/1     Running   0          3m49s   app=brupop-test,brupop.bottlerocket.aws/component=agent,controller-revision-hash=67b54459db,environment=beta,pod-template-generation=3
brupop-agent-qg4g9                           1/1     Running   0          2m37s   app=brupop-test,brupop.bottlerocket.aws/component=agent,controller-revision-hash=67b54459db,environment=beta,pod-template-generation=3
brupop-apiserver-6bb84bcb55-72xj9            1/1     Running   0          3m58s   app=brupop-test,brupop.bottlerocket.aws/component=apiserver,environment=beta,pod-template-hash=6bb84bcb55
brupop-apiserver-6bb84bcb55-fkhh6            1/1     Running   0          4m19s   app=brupop-test,brupop.bottlerocket.aws/component=apiserver,environment=beta,pod-template-hash=6bb84bcb55
brupop-apiserver-6bb84bcb55-mmcww            1/1     Running   0          4m8s    app=brupop-test,brupop.bottlerocket.aws/component=apiserver,environment=beta,pod-template-hash=6bb84bcb55
```

The labels are applied to the pods as expected!

Only thing I would kindly request here is that, could you also help update the READMEs to reflect this new value? 
Candidates:
- https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/deploy/charts/bottlerocket-update-operator/README.md
- https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/README.md

**Review by yeazelm — APPROVED** [review]

**Review by ytsssun — APPROVED** [review]

**Pull request merged**
