### PR TITLE
Add Brupop version support policy to README

### LINKED ISSUE #548: Question regarding Brupop's Support Policy
**Image I'm using:**
N/A

**Issue or Feature Request:**
This isn't an issue or a feature request, rather a question:

What is the support policy for Brupop in terms of which versions are supported at a given time and which version(s) are recommended to be installed on a prod cluster? I went through the documentation but could not find this information.

I would be grateful if someone could please guide me on this ^_^

### PR DESCRIPTION
**Pull request by mooneeb**
**Issue number:**
Closes #548 

**Description of changes:**
Add Brupop version support policy to README

**Testing done:**
None

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by mooneeb** [comment]
I wasn't sure what tests to run, or how to run them, so that's why i didn't run any tests. But, if they're necessary, I'll be happy to run them after receiving some guidance!

**Review by stmcginnis — APPROVED** [review]
Thanks!

**Comment by mooneeb** [comment]
> Thanks!

You're welcome! I'm glad I was able to help contribute ^_^ And thank for your guidance and help on this topic :)

**Review by cbgbt — APPROVED** [review]
Thank you!

**Pull request merged**
